FREE = 0
FIXED = 1

X = 1
Y = 2
ROTZ = 3

EIGEN_SOLVER_GEN_BAND_ARPACK = "genBandArpack"
EIGEN_SOLVER_SYMM_BAND_LAPACK = "symmBandLapack"
EIGEN_SOLVER_FULL_GEN_LAPACK = "fullGenLapack"

SYSTEM_BAND_GENERAL_SOE = "BandGen"
SYSTEM_BAND_SPD = "BandSPD"
SYSTEM_PROFILE_SPD = "ProfileSPD"
SYSTEM_SUPER_LU = "SuperLU"
SYSTEM_UMF_PACK = "UmfPack"
SYSTEM_FULL_GENERAL = "FullGeneral"
SYSTEM_SPARSE_SYM = "SparseSYM"
SYSTEM_SPARSE_GENERAL = "SparseGeneral"

NUMBERER_PLAIN = "Plain"
NUMBERER_RCM = "RCM"
NUMBERER_AMD = "AMD"

ANALYSIS_STATIC = "Static"
ANALYSIS_TRANSIENT = "Transient"
ANALYSIS_VARIABLE_TRANSIENT = "VariableTransient"
ANALYSIS_PFEM = "PFEM"

STEEL_01 = "Steel01"
ELASTIC_BILIN = "ElasticBilin"
BEAM_WITH_HINGES = "beamWithHinges"
FORCE_BEAM_COLUMN = "forceBeamColumn"
ELASTIC_BEAM_COLUMN = "elasticBeamColumn"
